version: "3"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=buff
      - POSTGRES_USER=buff
      - POSTGRES_PASSWORD=buff
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buff"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5


  proxy:
    image: nginx
    restart: always
    environment:
      - SERVER_PORT=8080
      - SERVER=server
      - DOLLAR=$
    volumes:
      - ./nginx-templates:/etc/nginx/templates
    ports:
      - 1234:80
    links:
      - server

  server:
    image: clowzed/buff:latest
    restart: always
    build: .
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
       - DATABASE_URL=postgresql://buff:buff@database/buff
       - REDIS_URL=redis://redis:6379
       - PORT=8080
       - STATUS_EXPIRATION_SECONDS=30
       - REALM=https://scrooge-china.com
       - SQLX_LOGGING=true
       - JWT_SECRET=secret
       - UPLOAD_FOLDER=/app/uploads
       - NEW_ORDERS_CHANNEL_NAME=new_orders_notifications
       - JWT_TTL=60
    volumes:
      - images:/app/uploads
      
  notifications:
    image: clowzed/buff-notifications:latest
    restart: always
    build: ./buff-notifications
    depends_on: 
      server:
        condition: service_started
    environment:
      - ADMIN_ID=
      - SITE_URL=http://proxy 
      - NEW_ORDERS_CHANNEL_NAME=new_orders_notifications
      - BOT_TOKEN=
      - REPOSITORY_STORAGE=/data/repository-storage.json
      - STATES_STORAGE=/data/users_states-sqlite.db
      - REDIS_URL=redis://redis:6379
    links:
      - server
    volumes:
      - data:/data
      
volumes:
  pgdata:
  images: 
  data:
