/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignModeratorRequest {
    #[serde(rename = "order_id")]
    pub order_id: String,
}

impl AssignModeratorRequest {
    pub fn new(order_id: String) -> AssignModeratorRequest {
        AssignModeratorRequest { order_id }
    }
}
