/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangePasswordRequest {
    #[serde(rename = "old_password")]
    pub old_password: String,
    #[serde(rename = "new_password")]
    pub new_password: String,
}

impl ChangePasswordRequest {
    pub fn new(old_password: String, new_password: String) -> ChangePasswordRequest {
        ChangePasswordRequest {
            old_password,
            new_password,
        }
    }
}
