/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginLinkResponse {
    #[serde(rename = "link")]
    pub link: String,
}

impl LoginLinkResponse {
    pub fn new(link: String) -> LoginLinkResponse {
        LoginLinkResponse { link }
    }
}
