/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "chat_id")]
    pub chat_id: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "sender")]
    pub sender: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Message {
    pub fn new(
        id: String,
        chat_id: String,
        text: String,
        sender: String,
        created_at: String,
    ) -> Message {
        Message {
            id,
            chat_id,
            text,
            sender,
            created_at,
        }
    }
}
