/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModeratorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "login")]
    pub login: String,
}

impl ModeratorResponse {
    pub fn new(id: String, login: String) -> ModeratorResponse {
        ModeratorResponse { id, login }
    }
}
