/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModeratorOrAdminInfo {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "login")]
    pub login: String,
    #[serde(rename = "role")]
    pub role: String,
}

impl ModeratorOrAdminInfo {
    pub fn new(id: String, login: String, role: String) -> ModeratorOrAdminInfo {
        ModeratorOrAdminInfo { id, login, role }
    }
}
