/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Order {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "payment_method")]
    pub payment_method: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "steam_id")]
    pub steam_id: String,
    #[serde(
        rename = "moderator_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub moderator_id: Option<Option<String>>,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "fixed_currency_rate")]
    pub fixed_currency_rate: String,
    #[serde(rename = "currency_symbol")]
    pub currency_symbol: String,
    #[serde(rename = "requisites_id")]
    pub requisites_id: String,
    #[serde(
        rename = "finished_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub finished_at: Option<Option<String>>,
}

impl Order {
    pub fn new(
        id: String,
        payment_method: String,
        status: String,
        created_at: String,
        steam_id: String,
        amount: String,
        fixed_currency_rate: String,
        currency_symbol: String,
        requisites_id: String,
    ) -> Order {
        Order {
            id,
            payment_method,
            status,
            created_at,
            steam_id,
            moderator_id: None,
            amount,
            fixed_currency_rate,
            currency_symbol,
            requisites_id,
            finished_at: None,
        }
    }
}
