/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistrationsInPeriodResponse {
    #[serde(rename = "count")]
    pub count: i32,
}

impl RegistrationsInPeriodResponse {
    pub fn new(count: i32) -> RegistrationsInPeriodResponse {
        RegistrationsInPeriodResponse { count }
    }
}
