/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveReviewRequest {
    #[serde(rename = "id")]
    pub id: i64,
}

impl RemoveReviewRequest {
    pub fn new(id: i64) -> RemoveReviewRequest {
        RemoveReviewRequest { id }
    }
}
