/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Review {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "steam_id")]
    pub steam_id: String,
    #[serde(rename = "review")]
    pub review: String,
    #[serde(rename = "stars")]
    pub stars: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Review {
    pub fn new(
        id: String,
        steam_id: String,
        review: String,
        stars: i32,
        created_at: String,
    ) -> Review {
        Review {
            id,
            steam_id,
            review,
            stars,
            created_at,
        }
    }
}
