/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewCountResponse {
    #[serde(rename = "video_review_count")]
    pub video_review_count: i32,
    #[serde(rename = "review_count")]
    pub review_count: i32,
}

impl ReviewCountResponse {
    pub fn new(video_review_count: i32, review_count: i32) -> ReviewCountResponse {
        ReviewCountResponse {
            video_review_count,
            review_count,
        }
    }
}
