/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendMessageResponse {
    #[serde(rename = "message")]
    pub message: Box<models::Message>,
    #[serde(rename = "images_ids")]
    pub images_ids: Vec<String>,
}

impl SendMessageResponse {
    pub fn new(message: models::Message, images_ids: Vec<String>) -> SendMessageResponse {
        SendMessageResponse {
            message: Box::new(message),
            images_ids,
        }
    }
}
