/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetRateRequest {
    #[serde(rename = "rate")]
    pub rate: String,
}

impl SetRateRequest {
    pub fn new(rate: String) -> SetRateRequest {
        SetRateRequest { rate }
    }
}
