/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusResponse {
    #[serde(rename = "statuses")]
    pub statuses: Vec<models::UserStatus>,
}

impl StatusResponse {
    pub fn new(statuses: Vec<models::UserStatus>) -> StatusResponse {
        StatusResponse { statuses }
    }
}
