/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeBounds {
    #[serde(rename = "start_datetime")]
    pub start_datetime: String,
    #[serde(rename = "end_datetime")]
    pub end_datetime: String,
}

impl TimeBounds {
    pub fn new(start_datetime: String, end_datetime: String) -> TimeBounds {
        TimeBounds {
            start_datetime,
            end_datetime,
        }
    }
}
