/*
 * buff
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserStatus {
    #[serde(rename = "steam_id")]
    pub steam_id: String,
    #[serde(rename = "is_online")]
    pub is_online: bool,
}

impl UserStatus {
    pub fn new(steam_id: String, is_online: bool) -> UserStatus {
        UserStatus {
            steam_id,
            is_online,
        }
    }
}
