//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub mod admin;
pub mod blacklisted;
pub mod chat;
pub mod currency_rate;
pub mod image;
pub mod message;
pub mod order;
pub mod requisites;
pub mod review;
pub mod sea_orm_active_enums;
pub mod social;
pub mod user;
pub mod video_review;
