//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub mod prelude;

pub mod admin;
pub mod blacklisted;
pub mod currency_rate;
pub mod order;
pub mod review;
pub mod sea_orm_active_enums;
pub mod user;
pub mod video_review;
