//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::{
    admin::Entity as Admin, blacklisted::Entity as Blacklisted, chat::Entity as Chat,
    currency_rate::Entity as CurrencyRate, image::Entity as Image, message::Entity as Message,
    order::Entity as Order, requisites::Entity as Requisites, review::Entity as Review,
    social::Entity as Social, user::Entity as User, video_review::Entity as VideoReview,
};
