//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::admin::Entity as Admin;
pub use super::blacklisted::Entity as Blacklisted;
pub use super::chat::Entity as Chat;
pub use super::currency_rate::Entity as CurrencyRate;
pub use super::image::Entity as Image;
pub use super::message::Entity as Message;
pub use super::order::Entity as Order;
pub use super::requisites::Entity as Requisites;
pub use super::review::Entity as Review;
pub use super::social::Entity as Social;
pub use super::user::Entity as User;
pub use super::video_review::Entity as VideoReview;
